version: '3.4'
name: ModularMonolith_Infrastructure

services:
  sqlserver:
    container_name: modularmonolith_sqlserver
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=YourSTRONG!Passw0rd
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver:/sqlserver
volumes: 
  sqlserver:
